language: node_js
node_js: 12.21.0
jdk:
  - oraclejdk8
addons:
  sonarcloud: true
script:
  — npm run coverage
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=hadamafer -Dsonar.projectKey=TP-IS -Dsonar.sources='./app' -X
after_success:
 — npm run coveralls